#!/bin/bash

# This script generates the AUTHORS file based on git history.

set -e

{
cat <<-'EOH'
# This file lists all individuals having contributed content to the repository.
# For how it is generated, see `hack/generate-authors.sh`.
EOH
echo

git log --format='%aN <%aE>' | sort -u

} > AUTHORS

echo "# File generated by hack/generate-authors.sh. DO NOT EDIT." > AUTHORS.temp
cat AUTHORS >> AUTHORS.temp
mv AUTHORS.temp AUTHORS

